import {
    attribute,
    autoGeneratedHashKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('Users')
export class User {
    @autoGeneratedHashKey()
    id: string;

    @attribute()
    email: string;

    @attribute()
    password: string;

    @attribute()
    userType: string;
}