import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";
import { embed } from "@aws/dynamodb-data-mapper";
import { bool } from "aws-sdk/clients/signer";

export class InjuryNote {
  @attribute()
  createdBy: string;
  @attribute({ defaultProvider: () => new Date() })
  createdOn: Date;
  @attribute()
  content: string;
}

@table("InjuryReports")
export class Injury {
  @autoGeneratedHashKey()
  id: string;

  @rangeKey({ defaultProvider: () => new Date() })
  createdAt: Date;

  @attribute()
  createdBy: string;

  @attribute()
  active: bool;

  @attribute()
  teamName: string;

  @attribute()
  teamId: string;

  @attribute()
  athleteName: string;

  @attribute()
  athleteId: string;

  @attribute()
  injuryDate: Date;

  @attribute()
  isSportsRelated: bool;

  @attribute()
  eventType: string;

  @attribute()
  position: string;

  @attribute()
  sideOfBody: string;

  @attribute()
  locationOnBody: string;

  @attribute()
  injuryType: string;

  @attribute()
  severity: number;

  @attribute()
  status: string;

  @attribute()
  mechanism: string;

  @attribute()
  injuryDescription: string;

  @attribute({ memberType: embed(InjuryNote) })
  otherNotes?: Array<InjuryNote>;

  @attribute({ memberType: embed(InjuryNote) })
  specialNotes?: Array<InjuryNote>;
}
