import {
  attribute,
  autoGeneratedHashKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";

@table("Teams")
export class Team {
  @autoGeneratedHashKey()
  id: string;

  @attribute()
  name: string;

  @attribute()
  season: string;

  @attribute()
  createdBy: string;

  @attribute({ defaultProvider: () => new Date() })
  createdAt: Date;

  @attribute()
  athletes: Array<string>;
}
