import {
  attribute,
  autoGeneratedHashKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";

@table("Users")
export class User {
  @autoGeneratedHashKey()
  id: string;

  @attribute()
  cwl: string;

  @attribute()
  firstName: string;

  @attribute()
  lastName: string;

  @attribute()
  email: string;

  @attribute()
  teams: string[];

  @attribute()
  role: string;
}
